# Generated by Django 5.0.3 on 2024-04-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinformation',
            name='product_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
