# Generated by Django 5.0.3 on 2024-04-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
