# Generated by Django 5.0.3 on 2024-04-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0002_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
