# Generated by Django 5.0.3 on 2024-04-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0003_normaluser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Designation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
