# Generated by Django 5.0.3 on 2024-04-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0004_doctor_department_doctor_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='Department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='Designation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
