# Generated by Django 5.0.3 on 2024-04-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0005_normaluser_department_normaluser_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='has_requested',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
