# Generated by Django 4.2.7 on 2024-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_medicineorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accnumber', models.IntegerField()),
                ('acctype', models.CharField(max_length=200)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
