# Generated by Django 5.0.3 on 2024-05-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_account_card_holder_account_cvv_account_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='card_holder',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='account',
            name='validity',
        ),
    ]
