# Generated by Django 5.0.3 on 2024-04-11 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autherization', '0004_doctor_department_doctor_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Dermatology', 'Dermatology')], max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autherization.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
