# Generated by Django 5.0.3 on 2024-05-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_booking_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_avail',
            field=models.BooleanField(default=False),
        ),
    ]
