# Generated by Django 5.0.3 on 2024-05-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_booking_department_alter_booking_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_avail',
            new_name='is_available',
        ),
    ]
