# Generated by Django 5.0.3 on 2024-04-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirylist',
            name='expmed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine_inventory'),
        ),
    ]
